@echo off

set "WEB_SDK=C:\WebSdk\"
set "bin=%WEB_SDK%bin\"
set "lib=%WEB_SDK%lib\"
set "etc=%WEB_SDK%etc\"
set "sdk=%lib%sdk\"
@REM nodejs
set "nvm=%lib%nvm\"
@REM mariadb
set "mariadb=%lib%mariadb\"
@REM pgsql
set "pgdb=%lib%pg\"
@REM web
set "nginx=%lib%nginx\"
set "httpd=%lib%httpd\bin\"
@REM php
set "php81=%lib%php\8.1\"
set "php82=%lib%php\8.2\"
set "php83=%lib%php\8.3\"
set "php84=%lib%php\8.4\"
set "php74=%lib%php\7.4\"
set "php56=%lib%php\5.6\"
set "php55=%lib%php\5.5\"
set "php=%php82%"
@REM python
set "pyversion=3.12.3"
set "py3=%lib%pyenv\versions\%pyversion%\"
@REM go
set "goversion=1.23.10"
set "gvm=%lib%gvm\"
set "go=%lib%go\"
set "ca=%lib%ca\"
@REM 7zip
set "unpack=%bin%7zr.exe"
set "elevate=%bin%elevate.exe"
set "daemonize=%sdk%daemonize.exe"
set "spawner=%sdk%php-cgi-spawner.exe"

